create table Furniture(
                          id int primary key generated by default as identity,
                          name varchar(100) not null,
                          price int not null,
                          sell_price int not null,
                          quantity int not null
);

create table "Order"(
    id int primary key generated by default as identity,
    id_user int references "User"(id) on delete cascade,
    id_furniture int references Furniture(id) on delete cascade,
    quantity int,
    created_at timestamp
);

create table "User"(
    id int primary key generated by default as identity,
    password varchar(100) not null,
    login varchar(100) not null,
    year_of_birth int not null,
    name varchar(100) not null,
    surname varchar(100) not null,
    email varchar(100) not null,
    role varchar not null
);

insert into "User"(password, login, name, surname, email, year_of_birth, role) VALUES ('1234Arina', 'ar.nka', 'Arina', 'Baranova', 'Arina@mail.com', 2003, 'admin');